name: GameMode
main: Zerko\GameMode
author: Zerko43
api: 3.0.0 3.5.0 3.8.0 4.0.0
version: 1.0
commands:
  gmc:
    description: Gamemode 1
    permission: gmc.cmd
  gms:
    description: Gamemode 0
    permission: gms.cmd
  gmt:
    description: Gamemode 3
    permission: gmt.use
  gma:
    description: Gamemode 2
    permission: gma.use
